### ISSUE TITLE
fatal: print to "standard output" failed (Broken pipe)

### ISSUE THREAD

**Issue by taymourheikal** [xuric/read-split-run#1]
Hi there,

Thanks for making this software readily available. Unfortunately, I've been having issues getting it to run.

After installation, configuration, installing bowtie indexes, and setting the BOWTIE_INDEXES variable using `export`, I still get an error like this:

```
rsr_batch_job.sh: sanity_check::$BOWTIE_PROGRAM=/read-split-run-master/bowtie/bowtie
rsr_batch_job.sh: sanity_check::$BOWTIE_PROGRAM=/read-split-run-master/bowtie/bowtie
head: write error: Broken pipe
head: write error
awk: (FILENAME=/read-split-run-master/rep1.fastq FNR=17940) fatal: print to "standard output" failed (Broken pipe)
/read-split-run-master/split.sh: line 49: ((: 51 >= /read-split-run-master/tmp/split / 2 : syntax error: operand expected (error token is "/read-split-run-master/tmp/split / 2 ")
split.sh: split_pairs::Don't know what do do with 5
awk: cmd. line:1: fatal: cannot open file `11' for reading (No such file or directory)
Traceback (most recent call last):
  File "/read-split-run-master/guess-encoding.py", line 90, in <module>
    main()
  File "/read-split-run-master/guess-encoding.py", line 81, in main
    print get_bowtie_option(valid[0])
IndexError: list index out of range
/read-split-run-master/bowtie.sh: line 88: /read-split-run-master/results - 1: syntax error: operand expected (error token is "/read-split-run-master/results - 1")
rsr_pipeline.sh: No bowtie file for . Cannot continue.
basename: missing operand
Try `basename --help' for more information.
basename: missing operand
Try `basename --help' for more information.

```
I'm using the following lines to submit the job:

```
export BOWTIE_INDEXES=/read-split-run-master/bowtie/indexes
read-split-run-master/rsr_batch_job.sh analytic hg19 "read-split-run-master/RNA_Tuni_Rep1_0h_merge.fastq" 11 5 3 30000 5 2 read-split-run-master/results
```

Any help would be much appreciated.
Thanks,
T

EDIT: I checked out the latest commit related to the files in src. Still getting this error though.

**Comment by kinnejeff** [comment]
Aaron - Do you have a suggestion?

If not I'll look into it.

Note that RSF is a newer version, and is at 
https://github.com/kinnejeff/read-split-fly
You might also be interested in looking at that.

-- Jeff

**Comment by aaronmcox** [comment]
There were multiple file I/O bugs fixed between RSR and RSF, so my first thought was to recommend a look at RSF. You should be able to get the results you're looking for, and it should be easier to run. In the README, it's said that the awk broken pipe is a known issue that doesn't affect execution, but maybe whoever dealt with that bug in the past was just lucky.


T, 

Would you mind sharing the operating system you're working on, and the output of the following command:
  bash --version

It would also help to see the log file.  if you execute the following command it should give you the last 2 log files created.  One may be empty, but if we could have the newest one that has content in it that would help.

ls -lht /read-split-run-master/logs | head -2

- Aaron

**Comment by taymourheikal** [comment]
`cat /etc/*-release` produces:
```
CentOS release 6.3 (Final)
CentOS release 6.3 (Final)
Rocks release 6.1 (Emerald Boa)
CentOS release 6.3 (Final)
```

`bash --version` produces:
`GNU bash, version 4.1.2(1)-release (x86_64-redhat-linux-gnu)`

And finally:
`ls: cannot access /read-split-run-master/logs: No such file or directory`

I'm using an HPC cluster, which is why I think that last command isn't working.

With regards to RSF, are memory efficiency and the BLAST+ functionality the only improvements? If not, is there an article available online for RSF similar to RSR's BMC Genomics paper (November 2015) [maybe comparing the two]?

Thanks,
T
